### PR TITLE
No nintendo switch

### PR DESCRIPTION
**Pull request by MemeHoovy**
I removed the app id thing for Nintendo switch and made compiling to switch impossible.
I mean, why would you wanna try that?
This is probably unnecessary and probably might get closed, but whatever, idrc.

### CODE REVIEW

**Comment by lunarcleint** [comment]
Lmao, w.i in the eShop 50$

**Comment by MemeHoovy** [comment]
> Lmao, w.i in the eShop 50$

💀

**Comment by cooldude47980597** [comment]
it wont work unless it’s a .tad file plug the cord into your computer drag the tad file and bring it into the nitendo

**Comment by MemeHoovy** [comment]
> it wont work unless it’s a .tad file plug the cord into your computer drag the tad file and bring it into the nitendo

that's the point of this PR, remove it from project.xml😐

**Pull request closed without merging**
